// There aren't any tests. Unit tests are great, but this was 
// meant to be a throwaway hack, so there aren't any here. This was
// generated by create-react-app and it is useful to see how it is
// done, so I'm keeping it.

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
